version: "3.4"
services:
  # mongodb is the data storage for the armory used to cache all characters.
  mongodb:
    image: mongo:4.2
    volumes:
      - ./mongodb-init:/docker-entrypoint-initdb.d
      - ./data/mongodb:/data/db
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      - AUTH=${MONGODB_AUTH}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
  # armory-api is the backend service that serves characters over http.
  armory-api:
    image: ghcr.io/nokka/d2-armory-api:latest
    volumes:
      - ./d2s/:/data/d2s
    ports:
      - "8090:80"
    environment:
      - MONGO_USERNAME=${MONGODB_API_USER}
      - MONGO_PASSWORD=${MONGODB_API_PASSWORD}
      - STATISTICS_USER=${STATISTICS_USER}
      - STATISTICS_PASSWORD=${STATISTICS_PASSWORD}
      - D2S_PATH=${D2_SAVE_PATH}
    depends_on:
      - mongodb
    entrypoint: sh -c "/app/armory"
  # armory-gui is the frontend used for the armory served by NGINX.
  armory-gui:
    image: ghcr.io/nokka/d2-armory-gui:latest
    ports:
      - "9000:80"
    depends_on:
      - armory-api
