version: "3.4"
services:
  mongodb:
    image: mongo:4.2
    volumes:
      - ./mongodb-init:/docker-entrypoint-initdb.d
      - ./data/mongodb:/data/db
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      - AUTH=${MONGODB_AUTH}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
